/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import login.koneksi;
/**
 *
 * @author FIQRY
 */
public class tescovid extends javax.swing.JFrame {

    

    public tescovid() {
        initComponents();
        tabelbio();
    }
    Statement st;
    Connection con = koneksi.getConnection();
    ResultSet rs;
    DefaultComboBoxModel modell;
    DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NIK = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ttl = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        notelpn = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ttes = new javax.swing.JTable();
        tanggaltes = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        hasiltes = new javax.swing.JComboBox<>();
        hasiltes1 = new javax.swing.JComboBox<>();
        hasiltes2 = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        jenistes = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("data pasien tes covid-19");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(379, 379, 379))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1057, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("nama lengkap");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 78, -1, -1));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 78, 192, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("NIK");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 116, -1, -1));
        jPanel1.add(NIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 117, 192, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("tanggal lahir");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 163, -1, -1));
        jPanel1.add(ttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 163, 192, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("jenis kelamin");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 202, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("no telepon");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 242, -1, -1));
        jPanel1.add(notelpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 242, 192, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("alamat");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 289, -1, -1));
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 289, 192, -1));

        simpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        simpan.setText("simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 284, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("tanggal tes");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 78, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("jenis tes");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 117, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("hasil tes");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 163, -1, -1));

        ttes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "nama", "NIK", "tanggal lahir", "gender", "telepon", "alamat", "tanggal tes", "jenis tes", "hasil tes"
            }
        ));
        ttes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ttes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 332, -1, -1));

        tanggaltes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggaltesActionPerformed(evt);
            }
        });
        jPanel1.add(tanggaltes, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 78, 200, -1));

        hapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hapus.setText("hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 289, -1, -1));

        kembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kembali.setText("kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 289, -1, -1));

        hasiltes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "positif", "negatif" }));
        jPanel1.add(hasiltes, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 163, 200, -1));

        hasiltes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "positif : gejala berat", "positif : gejala sedang", "positif : gejala ringan", "negatif" }));
        jPanel1.add(hasiltes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 163, 200, -1));

        hasiltes2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "positif : gejala berat", "positif : gejala sedang", "positif : gejala ringan", "negatif" }));
        jPanel1.add(hasiltes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 163, 200, -1));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "laki-laki", "perempuan" }));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 202, 192, -1));

        jenistes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCR", "RAPID" }));
        jPanel1.add(jenistes, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 116, 200, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\fiqry\\Videos\\136934.jpg")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1060, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tanggaltesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggaltesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggaltesActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        this.setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_kembaliActionPerformed

    private void ttesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttesMouseClicked
        int i = this.ttes.getSelectedRow();
        
        String nama = (String) model.getValueAt(i,0);
        this.nama.setText(nama);
        String nikk = (String) model.getValueAt(i,1);
        this.NIK.setText(nikk);
        String tanggal_lahir = (String) model.getValueAt(i,2);
        this.ttl.setText(tanggal_lahir);
        gender.setSelectedItem(ttes.getValueAt(ttes.getSelectedRow(), 3).toString());
        String notelpn = (String) model.getValueAt(i,4);
        this.notelpn.setText(notelpn);
        String alamt = (String) model.getValueAt(i,5);
        this.alamat.setText(alamt);  
        String tanggltes = (String) model.getValueAt(i,6);
        this.tanggaltes.setText(tanggltes);
        jenistes.setSelectedItem(ttes.getValueAt(ttes.getSelectedRow(), 7).toString());
        hasiltes.setSelectedItem(ttes.getValueAt(ttes.getSelectedRow(), 8).toString());

    }//GEN-LAST:event_ttesMouseClicked

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String namal = nama.getText();
        String nik = NIK.getText();
        String tanggallahirr = ttl.getText();
        Object jkelaminn = gender.getSelectedItem();
        String notelpon = notelpn.getText();
        String alamtt = alamat.getText();
        String taggltes = tanggaltes.getText();
        Object jnstes = jenistes.getSelectedItem();
        Object hsltes = hasiltes.getSelectedItem();
        
        try{
            con.createStatement().executeUpdate("insert into tescovid value ('" + namal + "','"+nik+"','"+tanggallahirr+"','"+jkelaminn+"','"+notelpon+"','"+alamtt+"','"+taggltes+"','"+jnstes+"','"+hsltes+"')");
            JOptionPane.showMessageDialog(null,"berhasil menyimpan");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null,"gagal menyimpan");
        }resetForm();
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try{
            con.createStatement().executeUpdate("delete from tescovid where nik = '"+NIK.getText()+"'");
            JOptionPane.showMessageDialog(null,"berhasil");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"gagal");
        }
        resetForm();
    }//GEN-LAST:event_hapusActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tescovid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tescovid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tescovid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tescovid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tescovid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIK;
    private javax.swing.JTextField alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton hapus;
    private javax.swing.JComboBox<String> hasiltes;
    private javax.swing.JComboBox<String> hasiltes1;
    private javax.swing.JComboBox<String> hasiltes2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenistes;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField notelpn;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField tanggaltes;
    private javax.swing.JTable ttes;
    private javax.swing.JTextField ttl;
    // End of variables declaration//GEN-END:variables
private void tabelbio(){
    String[] judul = {"nama","NIk","tanggal lahir","gender","telepon","alamat","tanggal tes","jenis tes","hasil tes"};
    model = new DefaultTableModel(judul,0);
    ttes.setModel(model);
    String sql = "select * from tescovid";
    
    try{
        rs = con.createStatement().executeQuery(sql);
        
        while(rs.next()){
            String nama=rs.getString("nama");
            String nik=rs.getString("nik");
            String tanggal_lahir=rs.getString("tanggal lahir");
            String gender=rs.getString("gender");
            String notelpn=rs.getString("no telpn");
            String alamat=rs.getString("alamat");
            String tgl_tes=rs.getString("tgl tes");
            String jenis_tes=rs.getString("jenis tes");
            String hasil_tes=rs.getString("hasil tes");
            
            String[] data = {nama,nik,tanggal_lahir,gender,notelpn,alamat,tgl_tes,jenis_tes,hasil_tes};
            model.addRow(data);
        }
    }catch(Exception e){
        System.out.println(e);
    }
    }
    public void resetForm(){
        

        nama.setText("");
        NIK.setText("");
        ttl.setText("");
        notelpn.setText("");
        alamat.setText("");
        tanggaltes.setText("");
        tabelbio();
        
    }
}


