/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

 
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import login.koneksi;
/**
 *
 * @author FIQRY
 */
public class vaksinasi extends javax.swing.JFrame {

    /**
     * Creates new form transaksi
     */
    public vaksinasi() {
        initComponents();
        tabelbio();
    }
    
    Statement st;
    Connection con = koneksi.getConnection();
    ResultSet rs;
    DefaultComboBoxModel modell;
    DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namalengkap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ttl = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        notelp = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tvaksin = new javax.swing.JTable();
        tglvaksin = new javax.swing.JTextField();
        jenisvaksin = new javax.swing.JComboBox<>();
        hapus = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatan = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jenisvaksin1 = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("data pasien vaksinasi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(407, 407, 407)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1057, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("nama lengkap");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 105, -1, -1));
        jPanel1.add(namalengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 105, 192, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("NIK");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 143, -1, -1));
        jPanel1.add(nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 143, 192, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("tanggal lahir");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 189, -1, -1));
        jPanel1.add(ttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 189, 192, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("jenis kelamin");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 228, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("no telepon");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 268, -1, -1));
        jPanel1.add(notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 268, 192, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("alamat");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 306, -1, -1));
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 306, 192, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 301, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("tanggal vaksinasi");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 105, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("jenis vaksin");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 143, -1, -1));

        tvaksin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "nama", "NIK", "tanggal lahir", "gender", "telepon", "alamat", "tanggal vaksinasi", "jenis vaksin", "catatan"
            }
        ));
        tvaksin.getTableHeader().setReorderingAllowed(false);
        tvaksin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvaksinMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tvaksin);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 344, -1, -1));
        jPanel1.add(tglvaksin, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 105, 200, -1));

        jenisvaksin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinovac", "AstraZeneca", "Moderna", "Pfizer", "Novavax" }));
        jenisvaksin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisvaksinActionPerformed(evt);
            }
        });
        jPanel1.add(jenisvaksin, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 143, 200, -1));

        hapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hapus.setText("hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("catatan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 189, -1, -1));

        catatan.setColumns(20);
        catatan.setRows(5);
        jScrollPane1.setViewportView(catatan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 187, 200, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, -1, -1));

        jenisvaksin1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinovac", "AstraZeneca", "Moderna", "Pfizer", "Novavax" }));
        jenisvaksin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisvaksin1ActionPerformed(evt);
            }
        });
        jPanel1.add(jenisvaksin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 143, 200, -1));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "laki-laki", "perempuan" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 227, 192, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\fiqry\\Videos\\136934.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1060, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1057, 521));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tvaksinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvaksinMouseClicked
        int i = this.tvaksin.getSelectedRow();
        
        String nama = (String) model.getValueAt(i,0);
        this.namalengkap.setText(nama);
        String nikk = (String) model.getValueAt(i,1);
        this.nik.setText(nikk);
        String tanggal_lahir = (String) model.getValueAt(i,2);
        this.ttl.setText(tanggal_lahir);
        gender.setSelectedItem(tvaksin.getValueAt(tvaksin.getSelectedRow(), 3).toString());
        String notelpn = (String) model.getValueAt(i,4);
        this.notelp.setText(notelpn);
        String alamt = (String) model.getValueAt(i,5);
        this.alamat.setText(alamt);
        String tangglvksn = (String) model.getValueAt(i,6);
        this.tglvaksin.setText(tangglvksn);
        jenisvaksin.setSelectedItem(tvaksin.getValueAt(tvaksin.getSelectedRow(), 7).toString());
        String cttn = (String) model.getValueAt(i,8);
        this.catatan.setText(cttn);
    
    }//GEN-LAST:event_tvaksinMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nama = namalengkap.getText();
        String nikk = nik.getText();
        String tanggallahir = ttl.getText();
        Object jkelamin = gender.getSelectedItem();
        String notelpn = notelp.getText();
        String alamt = alamat.getText();
        String tagglvksn = tglvaksin.getText();
        Object jnsvksin = jenisvaksin.getSelectedItem();
        String cttn = catatan.getText();
        
        try{
            con.createStatement().executeUpdate("insert into vaksinasi value ('" + nama + "','"+nikk+"','"+tanggallahir+"','"+jkelamin+"','"+notelpn+"','"+alamt+"','"+tagglvksn+"','"+jnsvksin+"','"+cttn+"')");
            JOptionPane.showMessageDialog(null,"berhasil menyimpan");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null,"gagal menyimpan");
        }resetForm();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jenisvaksinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisvaksinActionPerformed
        
    }//GEN-LAST:event_jenisvaksinActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try{
            con.createStatement().executeUpdate("delete from vaksinasi where nik = '"+nik.getText()+"'");
            JOptionPane.showMessageDialog(null,"berhasil");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"gagal");
        }
        resetForm();
    }//GEN-LAST:event_hapusActionPerformed

    private void jenisvaksin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisvaksin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisvaksin1ActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vaksinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vaksinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vaksinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vaksinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vaksinasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextArea catatan;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenisvaksin;
    private javax.swing.JComboBox<String> jenisvaksin1;
    private javax.swing.JTextField namalengkap;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField notelp;
    private javax.swing.JTextField tglvaksin;
    private javax.swing.JTextField ttl;
    private javax.swing.JTable tvaksin;
    // End of variables declaration//GEN-END:variables

    private void tabelbio(){
    String[] judul = {"nama","NIk","tanggal lahir","gender","telepon","alamat","tanggal vaksinasi","jenis vaksin","catatan"};
    model = new DefaultTableModel(judul,0);
    tvaksin.setModel(model);
    String sql = "select * from vaksinasi";
    
    try{
        rs = con.createStatement().executeQuery(sql);
        
        while(rs.next()){
            String nama=rs.getString("nama");
            String nik=rs.getString("nik");
            String tanggal_lahir=rs.getString("tanggal lahir");
            String gender=rs.getString("gender");
            String notelpn=rs.getString("no telpn");
            String alamat=rs.getString("alamat");
            String tgl_vaksin=rs.getString("tgl vaksin");
            String jenis_vaksin=rs.getString("jenis vaksin");
            String catatan=rs.getString("catatan");
            
            String[] data = {nama,nik,tanggal_lahir,gender,notelpn,alamat,tgl_vaksin,jenis_vaksin,catatan};
            model.addRow(data);
        }
    }catch(Exception e){
        System.out.println(e);
    }
    }
    public void resetForm(){
        

        namalengkap.setText("");
        nik.setText("");
        ttl.setText("");
        notelp.setText("");
        alamat.setText("");
        tglvaksin.setText("");
        catatan.setText("");
        tabelbio();
        
    }

}
 
